apiVersion: v1
kind: Secret
type: ibm/ibmc-s3fs
metadata:
  name: test-iam-secret
data:
  service-instance-id: <service instance id encoded in base64 (only needed when using auto-create-bucket)>
  api-key: <api key encoded in base64>
